### ISSUE TITLE
Error in displaying sources - failed to obtain information

### ISSUE THREAD

**Issue by arsaboo** [yokingma/search_with_ai#3]
I was able to get it working using Ollama. I am getting the results, but the sources are not displayed. 

![image](https://github.com/yokingma/search_with_ai/assets/18319734/772a559d-2b60-4fbe-8a49-5d8fdcf6c8bf)

Here's my `.env`
```yaml
# Bing search key
BING_SEARCH_KEY=
# Google search key
GOOGLE_SEARCH_KEY=
GOOGLE_SEARCH_ID=
# aliyun key
ALIYUN_KEY=
# Yi Key
YI_KEY=
# google gemini
GOOGLE_KEY=
GOOGLE_PROXY_URL=
# baidu
BAIDU_KEY=
BAIDU_SECRET=
# tencent KEY:ID, SECRET:KEY
TENCENT_KEY=
TENCENT_SECRET=
# openai key
OPENAI_KEY=
# openai proxy
OPENAI_PROXY_URL=https://api.openai.com/v1
# moonshot
MOONSHOT_KEY=
# lepthon key
LEPTON_KEY=
# Local llm: Ollama host, default http://localhost:11434
OLLAMA_HOST=http://192.168.2.162:11434
# Free search engine: https://www.searx.space/
SEARXNG_HOSTNAME=http://localhost:8080
```

**Comment by yokingma** [comment]
Hi, Are you using Docker for deployment?
1. please make sure SearXNG's API is working.
2. make sure this project can access SearXNG's API. 
3. you may need to modify SEARXNG_HOSTNAME in .env if you are using docker to deploy this project. (please ensure that this Docker can access the host machine's network.

**Comment by arsaboo** [comment]
I am using docker for deployment and followed the process listed in the docs. What should the SEARXNG_HOSTNAME be? How do I test it

**Comment by arsaboo** [comment]
or...do I have to have to deploy searxng separately?

**Comment by yokingma** [comment]
@arsaboo yes...  [searxng-docker](https://github.com/searxng/searxng-docker)

**Comment by arsaboo** [comment]
@yokingma So, I am running searxng using the following:
```yaml
version: "3.7"

services:
  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    networks:
      - searxng
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    networks:
      - searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
    ipam:
      driver: default

volumes:
  redis-data:
```
and I can access searxng using the IP address http://192.168.2.122:8080/

But I am still getting the same error. How do I change the SEARXNG_HOSTNAME?

It may be useful for you to create a complete docker compose file...to avoid such issues.

**Comment by arsaboo** [comment]
Same error even with:
```yaml
version: "3.7"

services:
  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"


volumes:
  redis-data:
```
