### ISSUE TITLE
大佬，能同步放一个在hub.docker.com上面去吗？

### ISSUE THREAD

**Issue by lbersl** [yokingma/search_with_ai#58]
大佬，能同步放一个在hub.docker.com上面去吗？
我git clone git到服务器以后，由于网络原因导致docker compose up -d下载不完软件包里面的软件，下载1小时也没下载完成。

**Comment by yokingma** [comment]
好，我预构建一个吧。

**Comment by lbersl** [comment]
> 好，我预构建一个吧。

多谢大佬，解决我的大问题

**Comment by lbersl** [comment]
我用了docker代理，但是就是某些步骤还是因为网络原因下载不了
![image](https://github.com/user-attachments/assets/87062333-89f6-48da-940e-05180551a45a)

**Comment by yokingma** [comment]
> 我用了docker代理，但是就是某些步骤还是因为网络原因下载不了 ![image](https://private-user-images.githubusercontent.com/151358725/371927131-87062333-89f6-48da-940e-05180551a45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzUxMzAsIm5iZiI6MTcyNzY3NDgzMCwicGF0aCI6Ii8xNTEzNTg3MjUvMzcxOTI3MTMxLTg3MDYyMzMzLTg5ZjYtNDhkYS05NDBlLTA1MTgwNTUxYTQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNTQwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODIyZTAyODEyOTczYTYyMDYyNDJjNDlkN2M1NTNlNDhhMTdjYWEyN2E3NTdkMThlNjQ4NDdmYmE5NDU2MjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hu-VhFKKTYxADRHA-hADJLnGqpbN9W2BlyGvOzAClcQ)

我在本机构建的时候也是会这样，只能多试几次

**Comment by lbersl** [comment]
麻烦大佬抽空预构一下docker版本的镜像，我去pull下来

**Comment by yokingma** [comment]
构建了一个镜像：```docker pull zacma/aisearch```

或者 docker compose:
```
services:
  search:
    container_name: aisearch
    # You can build locally
    # build: ./
    # Or you can use our pre-built image
    image: zacma/aisearch:latest
    volumes:
      - ./.env.docker:/app/.env
    ports:
      - "3000:3000"
    restart: always

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: always
    # ports:
    #   - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/

```

其中 ```.env.docker``` 文件和```docker-compose.yaml```在一起，只需要修改```.env.docker```配置文件重启容器就可以了。
